#!/usr/bin/env python3
"""Generate the Hermes error envelope as JSON Schema (spec Phase 1.2/1.4).

Reads the Pydantic models in bridge_errors.py and writes
`shared/hermes-errors.schema.json`, from which
`scripts/generate-hermes-contract.mjs` emits the zod validators and TS types.

Kept separate from the event schema because the two contracts fail differently:
an event-schema drift breaks rendering, an error-schema drift breaks every error
the product can show. They are regenerated by the same npm script and checked by
the same CI job.

MUST run with real pydantic — see generate_event_schema.py for why.

Usage:
    python3 hermes-bridge/generate_error_schema.py [--check]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Optional

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

REPO_ROOT = os.path.dirname(HERE)
OUTPUT_PATH = os.path.join(REPO_ROOT, "shared", "hermes-errors.schema.json")

try:
    from pydantic import BaseModel
except ImportError:  # pragma: no cover
    print("pydantic is required to generate the error schema", file=sys.stderr)
    raise SystemExit(2)

import bridge_errors as be

if not hasattr(BaseModel, "model_json_schema"):  # pragma: no cover
    print(
        "pydantic looks stubbed (no model_json_schema). Run this with real "
        "pydantic, e.g. hermes-bridge/.venv/bin/python.",
        file=sys.stderr,
    )
    raise SystemExit(2)


def build_schema() -> dict:
    # The envelope IS the document. model_json_schema() returns the top model
    # inline, with its nested pieces moved into $defs — so wrapping it in an allOf
    # $ref would point at a $defs entry that does not exist, and the Node side
    # would dereference to nothing and fall back to z.any().
    generated = be.HermesErrorEnvelope.model_json_schema(ref_template="#/$defs/{model}")
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://spark.local/schemas/hermes-errors.schema.json",
        "title": "Hermes error envelope",
        "description": (
            "The single error shape the hermes-bridge and the Node boundary emit "
            "to the UI. Generated from the Pydantic models in "
            "hermes-bridge/bridge_errors.py. Do not edit by hand; run "
            "`npm run gen:hermes-contract`."
        ),
        **generated,
        # Enumerated here rather than left to the model so the generated
        # TypeScript union is a closed `code` enum rather than `string`.
        "x-error-codes": list(be.ERROR_CODES),
        "x-retryable-codes": sorted(be.RETRYABLE_CODES),
        "x-generated-by": "hermes-bridge/generate_error_schema.py",
    }


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if stale")
    args = parser.parse_args()

    rendered = render(build_schema())

    if args.check:
        if not os.path.exists(OUTPUT_PATH):
            print(f"missing {OUTPUT_PATH}", file=sys.stderr)
            return 1
        with open(OUTPUT_PATH, encoding="utf-8") as handle:
            if handle.read() != rendered:
                print(
                    f"{os.path.relpath(OUTPUT_PATH, REPO_ROOT)} is stale. "
                    "Run `npm run gen:hermes-contract` and commit the result.",
                    file=sys.stderr,
                )
                return 1
        print("hermes error schema is up to date")
        return 0

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {os.path.relpath(OUTPUT_PATH, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
