// ─── `usage` event shape ─────────────────────────────────────────────────────
// Emitted once at the end of every chat stream (streamText, Hermes bridge
// proxy, direct compatible proxy) as a custom data-stream field:
//   {type:"usage", input_tokens, output_tokens, cached_input_tokens,
//    context_window, model}
// The client pre-scanner collects arbitrary custom fields from `data` parts,
// so the event is forwarded in the same field names.

import { getModelContextWindow } from '../model-context';

export interface UsageEvent {
  type: 'usage';
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
  context_window: number;
  model: string;
  /** Turn cost in USD, present only when the backend priced the turn. */
  cost_usd?: number;
}

export interface UsageEventSource {
  /** Tokens consumed by the prompt (input). */
  inputTokens: number;
  /** Tokens generated by the model (output). */
  outputTokens: number;
  /** Tokens served from a provider cache (0 when unknown). */
  cachedInputTokens?: number;
  /** Turn cost in USD when known (Hermes bridge, priced by pricing.py). */
  costUsd?: number;
}

/**
 * Build the `usage` custom field from a normalized token breakdown.
 * Context window is resolved server-side per model via model-context.ts.
 */
export function buildUsageEvent(
  source: UsageEventSource,
  model: string,
): UsageEvent {
  const inputTokens = Math.max(0, Math.floor(source.inputTokens) || 0);
  const outputTokens = Math.max(0, Math.floor(source.outputTokens) || 0);
  const cachedInputTokens = Math.max(0, Math.floor(source.cachedInputTokens ?? 0) || 0);

  const costUsd =
    typeof source.costUsd === 'number' && Number.isFinite(source.costUsd) && source.costUsd >= 0
      ? source.costUsd
      : undefined;

  return {
    type: 'usage',
    input_tokens: inputTokens,
    output_tokens: outputTokens,
    cached_input_tokens: cachedInputTokens,
    context_window: getModelContextWindow(model),
    model,
    ...(costUsd !== undefined ? { cost_usd: costUsd } : {}),
  };
}
